# settings.yaml

team:
  color: "blue"             # blue or red
  robot_id: 1

strategy:
  mode: "offensive"         # offensive | defensive | mixed
  aggression_level: 0.75    # 0.0 - passive, 1.0 - ultra aggressive

motors:
  left_pwm_pin: 17
  right_pwm_pin: 18
  max_speed: 0.85           # 0.0 - 1.0 (duty cycle)
  reverse_direction: false

vision:
  camera_index: 0
  ball_color_range:
    lower: [10, 100, 100]   # HSV lower bound
    upper: [25, 255, 255]   # HSV upper bound
  min_contour_area: 500

imu:
  i2c_bus: 1
  address: 0x68             # Common for MPU6050
  gyro_threshold: 0.05

logging:
  level: "INFO"             # DEBUG, INFO, WARNING, ERROR
  save_to_file: true
  log_path: "data/logs/runtime.log"
